config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   get 'appointments/index'
   root 'appointments#index'
   post 'appointmentsSearch', to: 'appointments#search'
   get 'appointmentsSearch', to: 'appointments#search.json'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /appointments/search
  # POST /appointments/search.json
  def search
    @appointment = Appointment.new( appointment_params )
    @appointments = Appointment.where( "description LIKE ?", "%#{@appointment.description}%" )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:description, :date, :recursive, :recurseDays)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :recursive %>
    <%= form.check_box :recursive %>
  </div>

  <div class="field">
    <%= form.label :recurseDays %>
    <%= form.number_field :recurseDays %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Date</th>
      <th>Recursive</th>
      <th>Recursedays</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.description %></td>
        <td><%= appointment.date %></td>
        <td><%= appointment.recursive %></td>
        <td><%= appointment.recurseDays %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @appointment.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Recursive:</strong>
  <%= @appointment.recursive %>
</p>

<p>
  <strong>Recursedays:</strong>
  <%= @appointment.recurseDays %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <style>
* {box-sizing: border-box;}
ul {list-style-type: none;}
body {font-family: Verdana, sans-serif;}
.month {
    padding: 70px 25px;
    width: 100%;
    background: #1abc9c;
    text-align: center;
}
.month ul {
    margin: 0;
    padding: 0;
}
.month ul li {
    color: white;
    font-size: 20px;
    text-transform: uppercase;
    letter-spacing: 3px;
}
.month .prev {
    float: left;
    padding-top: 10px;
}
.month .next {
    float: right;
    padding-top: 10px;
}
.weekdays {
    margin: 0;
    padding: 10px 0;
    background-color: #ddd;
}
.weekdays li {
    display: inline-block;
    width: 13.6%;
    color: #666;
    text-align: center;
}
.days {
    padding: 10px 0;
    background: #eee;
    margin: 0;
}
.days li {
    display: inline-block;
    width: 22%;
    text-align: center;
    margin-bottom: 5px;
    margin-top:5px;
    font-size:12px;
    color: #777;
}
.days li .active {
    padding: 5px;
    background: #1abc9c;
    color: white !important
}
/* Add media queries for smaller screens */
@media screen and (max-width:720px) {
    .weekdays li, .days li {width: 13.1%;}
}
@media screen and (max-width: 420px) {
    .weekdays li, .days li {width: 12.5%;}
    .days li .active {padding: 2px;}
}
@media screen and (max-width: 290px) {
    .weekdays li, .days li {width: 12.2%;}
}
</style>
    
    <title>Bil495Calendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= yield %>
	
    <div class="month">      
    <ul>
      <li class="prev" onClick=(changeMonth(0))>&#10094;</li>
      <li class="next" onClick=(changeMonth(1))>&#10095;</li>
      <li id="month">
      <script>
      
        	var months=["","JANUARY","FEBRUARY","MARCH","APRIL","MAY","JUNE","JULY","AUGUST","SEPTEMBER","OCTOBER","NOVEMBER","DECEMBER"];
        	var currentDate = new Date(); 
			currentMonth= currentDate.getMonth()+1;
			currentYear= currentDate.getFullYear();
      		function changeMonth(index){
      			if(index==0){
      				document.getElementById("month").innerHTML = getPreviousMonth() + " " + currentYear;
					document.getElementById("days").innerHTML= drawDays();
      			}
      			else{
      				document.getElementById("month").innerHTML = getNextMonth() + " " + currentYear;
					document.getElementById("days").innerHTML= drawDays();
      			}
      		}
    		function getCurrentMonth(){
	 			 return months[currentMonth];
    		}
    		function getPreviousMonth(){
    			if(currentMonth!=1)
    				currentMonth-=1;
				else{
					currentMonth=12;
					currentYear-=1;
				}
    			return months[currentMonth];
    		}
    		function getNextMonth(){
    			if(currentMonth!=12)
    				currentMonth+=1;
				else{
					currentMonth=1;
					currentYear+=1;
				}
    			return months[currentMonth];
    		}
			
      		document.getElementById("month").innerHTML = getCurrentMonth() + " " + currentYear; 
      
      </script>
      </li>
    </ul>
    </div> 

  <ul class="days" id="days"> 
  
  <script>
  function GetJSON(yourUrl){
    var Httpreq = new XMLHttpRequest(); // a new request
    Httpreq.open("GET",yourUrl,false);
    Httpreq.send(null);
    return Httpreq.responseText;          
  }

  jsonObject=JSON.parse(GetJSON(window.location.origin + '/appointments.json'));
  
  var monthToDaysMap = new Map();
  monthToDaysMap.set(1, 31);
  monthToDaysMap.set(2, 28);
  monthToDaysMap.set(3, 31);
  monthToDaysMap.set(4, 30);
  monthToDaysMap.set(5, 31);
  monthToDaysMap.set(6, 30);
  monthToDaysMap.set(7, 31);
  monthToDaysMap.set(8, 31);
  monthToDaysMap.set(9, 30);
  monthToDaysMap.set(10, 31);
  monthToDaysMap.set(11, 30);
  monthToDaysMap.set(12, 31);

  function drawDays(){
    var d='';
	
    for(i=1;i<=getDaysOfMonth(currentMonth,currentYear);i++){
      d=d+'<li id='+i+' onclick=\"showApps(Number(id), Number(currentMonth), Number(currentYear))\">'+i;
      var y;
      for(y=0;y<jsonObject.length;y++)
	  {
		var appointDay = getAppointDay(y);
		var appointMonth = getAppointMonth(y);
		var appointYear = getAppointYear(y);
        if
		( 
			(
				( appointDay==i 
				||	(
						(i > appointDay) 
						&& (i - appointDay) % jsonObject[y].recurseDays == 0
					)
				)
				&& appointMonth==currentMonth
				&& appointYear==currentYear
			)
			|| jsonObject[y].recurseDays > 0
				&& dayHasPastRecursiveAppoint(i,currentMonth,currentYear, appointDay, appointMonth, appointYear, jsonObject[y].recurseDays)
		)
		{
          d= d+"#";
        }
      }
      d=d+'</li>';   
    } 
    return d;
  }

  function dayHasPastRecursiveAppoint(day, month, year, appointDay, appointMonth, appointYear, recurse)
  { 
	var dayTotal = 0;
	if (appointYear<year || (appointYear==year && appointMonth<month))
		{
			var i = appointMonth;
			var j = appointYear;
			while((i!=month) || (j!=year))
			{
				if (i == appointMonth && j == appointYear)
					dayTotal += (getDaysOfMonth(appointMonth,appointYear) - appointDay);
				else
					dayTotal += getDaysOfMonth(i,j);
									
				i++;
								
				if(i == 13)
				{
					i = 1;
					j++;
				}
			}
			dayTotal += day;
			
			return ((dayTotal%recurse) == 0)
		}
	else return false;
  }
	
document.getElementById("days").innerHTML= drawDays();
  
  function showApps(day,month,year)
  {
	var result='';
    for(var y=0;y<jsonObject.length;y++)
	{
		var appointDay = getAppointDay(y);
		var appointMonth = getAppointMonth(y);
		var appointYear = getAppointYear(y);
		
		if
		(
			(
				appointDay==day 
				&& appointMonth==month
				&& appointYear==year
			)				
			||
			(
				jsonObject[y].recursive
				&&
				(
					appointDay<=day 
					&& appointMonth==month
					&& appointYear==year
					&& (day - appointDay) % jsonObject[y].recurseDays==0
				)
				||
				(
					dayHasPastRecursiveAppoint(day, month, year, appointDay, appointMonth, appointYear, jsonObject[y].recurseDays)
				)
			)
		)
		{
			result+=getAppointTime(y)+"--"+jsonObject[y].description+'\n';
        }
	}	
    alert(result); 
  }

  function search(keyword){
  	  var xhttp = new XMLHttpRequest();
      xhttp.open("POST",window.location.origin + '//appointmentsSearch.json', true);
      xhttp.setRequestHeader("Content-type", "application/json");
      var data = JSON.stringify({"description":keyword, "date":"2018-06-26T00:00:00.000Z", "recursive":false, "recurseDays":null});
          xhttp.onreadystatechange = function () {
          if (xhttp.readyState === 4 && xhttp.status === 200) {
              var appointments = JSON.parse(xhttp.responseText);
              var found = ""
              for (i in appointments) {
                  found += appointments[i].description + ": " + appointments[i].date.substr(0, appointments[i].date.length - 5) + "\n";
              }
              alert(found);
          }
      };
      xhttp.send(data)
  }
  
  function getAppointDay(y) {
	return Number(jsonObject[y].date.substring(8,10));
  }
  
  function getAppointMonth(y) {
	return Number(jsonObject[y].date.substring(5,7));
  }
  
  function getAppointYear(y) {
	return Number(jsonObject[y].date.substring(0,4));
  }
  
  function getAppointTime(y) {
	return jsonObject[y].date.substring(11,16);
  }
  
  function getDaysOfMonth(month,year){
	if( month == 2 && (year%4) == 0)
		return 29;
	else
		return monthToDaysMap.get(month);	
  }

  </script>

  </ul>

  <form onsubmit = "search(keyword.value);return false">
      Search:<br>
      <input type = "text" name = "keyword" value = "Enter a keyword to search">
      <input type = "submit" value = "Submit">
  </form> 

  </body>
 
  
</html>